# Generated by Django 3.2 on 2023-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=16, verbose_name='plate number')),
                ('model', models.CharField(max_length=64, verbose_name='model')),
                ('color', models.CharField(max_length=16, verbose_name='color')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
                'db_table': 'car',
            },
        ),
    ]
