# Generated by Django 3.2 on 2023-06-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='province',
            name='latitude',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='province',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
    ]
