# Generated by Django 3.2 on 2023-06-09 21:40

import UserProfile.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=UserProfile.utils.avatar_upload_path, verbose_name='driver avatar'),
        ),
    ]
